IoTSensor/src/com/sap/iot/mangedBean/DataSensorMB.java
package com.sap.iot.mangedBean;

import java.sql.SQLException;
import java.util.*;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import com.sap.iot.entidad.*;
import com.sap.iot.servicios.*;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.CategoryAxis;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.LineChartModel;
import org.primefaces.model.chart.MeterGaugeChartModel;
import org.primefaces.model.map.MapModel;



@ManagedBean(name = "dataSensor")
@ViewScoped
public class DataSensorMB {

	private MeterGaugeChartModel GaugeTempModel;
	private MeterGaugeChartModel GaugeHumidityModel;
	private LineChartModel lineGraphic;
	private LineChartModel lineGraphicHumedad;
	private ChartSeries series1;
	private ChartSeries serieHumedad;
	private MapModel simpleModel;
	
	@ManagedProperty("#(param.nameId)")
	private String deviceName;
	
	private boolean alertaUso, aparecioAlerta, stop;
	private DataBaseOperations dataBaseOperations;
	private static Logger logger = LogManager.getLogger(DataSensorMB.class.getName());
	
	List<Number> datos = new ArrayList<Number>();


	public DataSensorMB() {
		

	}
	
	//metodo que inicializa las graficas y la conexion a base de datos
	@PostConstruct
	public void init() {

		try {
			InitialContext ctx = new InitialContext();
			DataSource ds = (DataSource) ctx.lookup("java:comp/env/jdbc/dataSource2");
			alertaUso = false;
			setAparecioAlerta(false);
			dataBaseOperations = new DataBaseOperations(ds);
			createGraphicTemp();
			createGraphicHumidity();
			createGaugeTemperature();
			createGaugeHumidity();
			
		} catch (SQLException sqlException) {
			sqlException.printStackTrace();
			
			logger.log(Level.ERROR, "Error" + sqlException.getMessage());
		} catch (NamingException enException) {
			enException.printStackTrace();
			logger.log(Level.ERROR, "Error al buscar conexion " + enException.getMessage());
		}
	}

	// retorna lista de los datos almacenados en la tabla
	public List<Entidad> getData() {
		logger.info("Prueba mensage");
		try {
			return dataBaseOperations.getData();
			
		} catch (Exception e) {
			logger.log(Level.ERROR, "Error en getData(): " + e.getMessage());
			e.printStackTrace();
		}
		return null;
	}

	// trae la data almacenada en el la clase DataBaseOperations en el metodo getTemperatura

	public MeterGaugeChartModel getGaugeTempModel() throws Exception {

		double temp = Double.parseDouble(dataBaseOperations.getTemperatura(getDeviceName()));

		if (temp >= 27) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Mensaje", "Detalles del mensaje"));
			setAlertaUso(true);
			stop();
		} else {
			setAlertaUso(false);
		}

		GaugeTempModel.setValue(temp);
		GaugeTempModel.setTitle("Temperatura "+ temp + " °C");
		return GaugeTempModel;
	}
	//trae los datos de la clase DataBaseOperation del metodo getHumidity
	public MeterGaugeChartModel getGaugeHumidityModel() throws Exception {

		double humidity = Double.parseDouble(dataBaseOperations.getHumidity(getDeviceName()));
		GaugeHumidityModel.setValue(humidity);
		GaugeHumidityModel.setTitle("Humedad " + humidity + " %");
		return GaugeHumidityModel;
	}

	public void stop() {
		if (isAlertaUso()) {
			setStop(true);
		}
	}
	
//crea el grafico de temperatura
	private void createGaugeTemperature() {
		List<Number> intervals = new ArrayList<Number>() {

			private static final long serialVersionUID = 1L;

			{
				add(10);
				add(20);
				add(30);
				add(40);
			}
		};
		GaugeTempModel = new MeterGaugeChartModel(10, intervals);
		GaugeTempModel.setSeriesColors("66cc66,93b75f,E7E658,cc6666");
		GaugeTempModel.setIntervalOuterRadius(100);
	}
	
//crea el grafico humedad
	private void createGaugeHumidity() {
		List<Number> intervals = new ArrayList<Number>() {

			private static final long serialVersionUID = 1L;

			{
				add(20);
				add(45);
				add(60);
				add(100);
			}
		};
		GaugeHumidityModel = new MeterGaugeChartModel(10, intervals);
		GaugeHumidityModel.setTitle("Humedad");
		GaugeHumidityModel.setSeriesColors("66cc66,93b75f,E7E658,cc6666");
		GaugeHumidityModel.setIntervalOuterRadius(100);
	}

	//crea el grafico lineal de la temperatura
	public void createGraphicTemp(){
		
		lineGraphic = new LineChartModel();
		series1 = new ChartSeries();
		series1.setLabel("Grados °C");
		
		lineGraphic.addSeries(series1);
		
		lineGraphic.setTitle("Temperatura / hora");
		lineGraphic.setLegendPosition("e");
		lineGraphic.setAnimate(true);
		lineGraphic.setShadow(true);
        lineGraphic.getAxes().put(AxisType.X, new CategoryAxis("Horas"));
        
        Axis ejeY = lineGraphic.getAxis(AxisType.Y);
        ejeY.setLabel("Temperatura");
        ejeY.setMin(0);
        ejeY.setMax(50);
        
        Axis ejeX = lineGraphic.getAxis(AxisType.X);
        ejeX.setLabel("Hora/Dia");
        ejeX.setTickAngle(-50);
        ejeX.setMin(0);
        ejeX.setMax(24);
	}
	//crea el grafico lineal de la humeedad
	public void createGraphicHumidity(){
		
		lineGraphicHumedad = new LineChartModel();
		serieHumedad = new ChartSeries();
		serieHumedad.setLabel("% Humedad");
		
		lineGraphicHumedad.addSeries(serieHumedad);
		lineGraphicHumedad.setTitle("Humedad / hora");
		lineGraphicHumedad.setLegendPosition("e");
		lineGraphicHumedad.setAnimate(true);
		lineGraphicHumedad.setShadow(true);
		lineGraphicHumedad.getAxes().put(AxisType.X, new CategoryAxis("Horas"));
        
        Axis ejeY = lineGraphicHumedad.getAxis(AxisType.Y);
        ejeY.setLabel("Humedad");
        ejeY.setMin(0);
        ejeY.setMax(100);
        System.out.println("ha llegado");
        Axis ejeX = lineGraphicHumedad.getAxis(AxisType.X);
        ejeX.setLabel("Hora/Dia");
        ejeX.setTickAngle(-50);
	}
	
	//trae los datos guardados en el metodo getTemperatureByHour correspondiente al dispositivo y la envia al grafico lineal
	public LineChartModel getLineGraphic(){
		 
         try {
			List<Entidad> lista =dataBaseOperations.getTemperatureByHour(getDeviceName());
		
			for (Entidad data : lista) {
				series1.set(data.getHora(), Double.parseDouble(data.getC_TEMPERATURA()));
			}
         
         } catch (Exception e) {
        	 logger.log(Level.ERROR, "Error en getLineGraphic): " + e.getMessage());
			e.printStackTrace();
		 }
	     return lineGraphic;
	}	
	
	//trae los datos guardados en el metodo getHumidityByHour correspondiente al dispositivo y la envia al grafico lineal
	public LineChartModel getLineGraphicHumedad(){
		 
        try {
			List<Entidad> lista =dataBaseOperations.getHumidityByHour(getDeviceName());
		
			for (Entidad data : lista) {
				serieHumedad.set(data.getHora(), Double.parseDouble(data.getC_HUMEDAD()));
			}
        
        } catch (Exception e) {
        	logger.log(Level.ERROR, "Error en getLineGraphicHumedad(): " + e.getMessage());
			e.printStackTrace();
		 }
	     return lineGraphicHumedad;
	}	

	//recive la accion desencadenada en la vista para enviar el email, usando como objeto la clase Email
	public void sendEmail(ActionEvent actionEvent) {

		Email email = new Email();
		FacesMessage message;

		if (email.createPropsEmail()) {
			message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Email enviado correctamente", null);
		} else {
			message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error: El email no se pudo enviar", null);
		}
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	// getters y setters

	public MapModel getSimpleModel() {
		return simpleModel;
	}

	public boolean isAlertaUso() {
		return alertaUso;
	}

	public void setAlertaUso(boolean alertaUso) {
		this.alertaUso = alertaUso;
	}

	public boolean isAparecioAlerta() {
		return aparecioAlerta;
	}

	public void setAparecioAlerta(boolean aparecioAlerta) {
		this.aparecioAlerta = aparecioAlerta;
	}

	public boolean isStop() {
		return stop;
	}

	public void setStop(boolean stop) {
		this.stop = stop;
	}

	public void setLineGraphic(LineChartModel lineGraphic) {
		this.lineGraphic = lineGraphic;
	}
	
	public void setLineGraphicHumedad(LineChartModel lineGraphicHumedad) {
		this.lineGraphicHumedad = lineGraphicHumedad;
	}

	public String getDeviceName() {
		return deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}
}

IoTSensor/src/com/sap/iot/mangedBean/DatosHotelMB.java
package com.sap.iot.mangedBean;

import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.MeterGaugeChartModel;

import com.sap.iot.entidad.Calculos;
import com.sap.iot.servicios.DataBaseOperations;

@ManagedBean(name = "dataSensorHotel")
@ViewScoped
public class DatosHotelMB {

	/*
	 * @ManagedProperty("#(param.nameId)") private String deviceName;
	 */

	private MeterGaugeChartModel gaugeHotelModel;
	private MeterGaugeChartModel gaugeHotelModelCalculo;
	private BarChartModel barModel;
	private DataBaseOperations dataBaseOperations;

	private double consumo, ahorro;
	private Calculos calcularConsumo;
	private Calculos calcularAhorro;
	private boolean estado;

	private static final Logger logger = LogManager.getLogger(DatosHotelMB.class.getName());

	public DatosHotelMB() {

	}

	@PostConstruct
	public void init() {

		try {
			InitialContext ctx = new InitialContext();
			DataSource ds = (DataSource) ctx.lookup("java:comp/env/jdbc/dataSource2");

			dataBaseOperations = new DataBaseOperations(ds);
			createGaugeHotel();
			estado = false;
			createGaugeCalculo();
			createBarModel();
			// backgroundColor("white");
			logger.log(Level.INFO, "Info logger");

		} catch (SQLException sqlException) {
			sqlException.printStackTrace();
			logger.log(Level.WARN, "Error" + sqlException.getMessage());
		} catch (NamingException enException) {
			enException.printStackTrace();
			logger.log(Level.WARN, "Error al buscar conexion " + enException.getMessage());
		}
	}

	// trae los datos de la clase DataBaseOperation del metodo getDataLuz
	public MeterGaugeChartModel getGaugeHotelModel() throws Exception {

		int var = 0;
		int luz = Integer.parseInt(dataBaseOperations.getDataLuz());
		System.out.println(luz);

		int res = luz / 10;
		gaugeHotelModel.setValue(res);
		gaugeHotelModel.setTitle("Nivel de Oscuridad " + res + " %");

		calcularConsumo = dataBaseOperations.getConsumo();
		calcularAhorro = dataBaseOperations.getAhorro();

		/*
		 * if (res > 20 && (int) gaugeHotelModelCalculo.getValue() == 100) {
		 * cal.setConsumo(calcularConsumo.getConsumo() + 60);
		 * cal.setAhorro(calcularAhorro.getAhorro() + 0);
		 * dataBaseOperations.actualizarConsumoAhorro(cal); }
		 */

		if (res <= 20) {
			var = 100;

			// cont.Contar();
			gaugeHotelModelCalculo.setValue(var);
			gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var + "%");
			
		}

		if (res >= 21 && res <= 40) {
			var = 70;
			gaugeHotelModelCalculo.setValue(var);
			gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var + "%");
			
		}

		if (res >= 41 && res <= 60) {
			var = 50;
			gaugeHotelModelCalculo.setValue(var);
			gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var + "%");
	
		}

		if (res >= 61 && res <= 80) {
			var = 30;
			gaugeHotelModelCalculo.setValue(var);
			gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var + "%");
			
		}

		if (res >= 81 && res <= 110) {
			var = 10;
			gaugeHotelModelCalculo.setValue(var);
			gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var + "%");
		}

		return gaugeHotelModel;
	}

	public MeterGaugeChartModel getGaugeHotelCal(int var) throws NumberFormatException, SQLException {
		gaugeHotelModelCalculo.setValue(var);
		gaugeHotelModelCalculo.setTitle("Nivel de ahorro " + var);

		return gaugeHotelModelCalculo;

	}

	// crea el grafico lineal

	private BarChartModel initBarModel() {
		BarChartModel model = new BarChartModel();
		
		 Date utilDate = new Date(); //fecha actual
		  long lnMilisegundos = utilDate.getTime();
		  Date sqlDate = new Date(lnMilisegundos);
		  Time sqlTime = new Time(lnMilisegundos);

		try {
			Calculos lista = dataBaseOperations.getAhorro();
			Calculos listaConsumo = dataBaseOperations.getConsumo();

			ChartSeries ahorro = new ChartSeries();
			ahorro.setLabel("Ahorro");

			
			ahorro.set(sqlDate, lista.getAhorro());
		

			ChartSeries consumo = new ChartSeries();
			consumo.setLabel("Consumo");

			consumo.set(sqlDate, listaConsumo.getConsumo());
			
			model.addSeries(ahorro);
			model.addSeries(consumo);

		} catch (Exception e) {
			e.printStackTrace();
		}

		return model;
	}

	// crea el modelo de luz
	private void createGaugeHotel() {
		List<Number> intervals = new ArrayList<Number>() {

			private static final long serialVersionUID = 1L;

			{
				add(20);
				add(40);
				add(60);
				add(80);
				add(100);
			}
		};
		gaugeHotelModel = new MeterGaugeChartModel(0, intervals);
		gaugeHotelModel.setSeriesColors("E5E5E5,C4C4C4,B0B0B0,878787,5E5E5E");
		gaugeHotelModel.setIntervalOuterRadius(100);
	}

	private void createGaugeCalculo() {
		List<Number> intervals = new ArrayList<Number>() {

			private static final long serialVersionUID = 1L;

			{
				add(20);
				add(40);
				add(60);
				add(80);
				add(100);
			}
		};
		gaugeHotelModelCalculo = new MeterGaugeChartModel(100, intervals);
		gaugeHotelModelCalculo.setSeriesColors("E5E5E5,C4C4C4,B0B0B0,878787,5E5E5E");
		gaugeHotelModelCalculo.setIntervalOuterRadius(100);
	}

	private void createBarModel() {
		
		barModel = initBarModel();

		barModel.setTitle("Relacion consumo/ahorro");
		barModel.setLegendPosition("e");

		Axis yAxis = barModel.getAxis(AxisType.Y);
		yAxis.setLabel("W/h");

		Axis xAxis = barModel.getAxis(AxisType.X);
		xAxis.setLabel("Dia");
		xAxis.setMin(0);
		xAxis.setMax(500);
	}


	// GETTERS Y SETTERS

	public MeterGaugeChartModel getGaugeHotelSimpleModel() {
		return gaugeHotelModel;
	}

	public void setGaugeHotelModel(MeterGaugeChartModel GaugeHotelModel) {
		gaugeHotelModel = GaugeHotelModel;
	}

	public MeterGaugeChartModel getGaugeHotelCalModel() {
		return gaugeHotelModelCalculo;
	}

	public void setGaugeHotelCalModel(MeterGaugeChartModel GaugeHotelModelCalculo) {
		gaugeHotelModelCalculo = GaugeHotelModelCalculo;
	}

	public BarChartModel getBarModel() {
		return barModel;
	}

	public void setBarModel(BarChartModel barModel) {
		this.barModel = barModel;
	}

	public double getAhorro() {
		return ahorro;
	}

	public void setAhorro(double ahorro) {
		this.ahorro = ahorro;
	}

	public double getConsumo() {
		return consumo;
	}

	public void setConsumo(double consumo) {
		this.consumo = consumo;
	}

	public boolean getEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Calculos getCalcularConsumo() {
		return calcularConsumo;
	}

	public void setCalcularConsumo(Calculos calcularConsumo) {
		this.calcularConsumo = calcularConsumo;
	}

	public Calculos getCalcularAhorro() {
		return calcularAhorro;
	}

	public void setCalcularAhorro(Calculos calcularAhorro) {
		this.calcularAhorro = calcularAhorro;
	}


}

IoTSensor/WebContent/Visual.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>


</h:head> 
<body >


<p:panel style="#{dataSensorHotel.backgroundColor}" ></p:panel>




</body> 
</html>

IoTSensor/WebContent/indexHotel.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<title>Ambiente Luminico</title>
	<link rel="stylesheet" href="recursos/css/estilosHotel.css" />
	<link rel="icon" type="image/ico"
		href="recursos/images/icons/Seidor_icon.ico" />


	<style type="text/css">
</style>

	<script>
	

            $(document).ready(function () {

                $("body").hide().fadeIn(1000);
				

            });


        </script>
</h:head>
<body>

	<div class="cover"
		style="background-image: url('recursos/images/background.png');">
		<div class="content">
			<div id="figure" class="logo">
				<img src="recursos/images/logoBlanco.png" alt="" width="300" />
			</div>
		</div>
	</div>


	<div id="navegacionHotel">
		<div id="nav">
			<ul>
				<li><p:link styleClass="a" outcome="index" value="Salir"></p:link></li>
				<li><p:link styleClass="a" outcome="Visual" value="Ver"></p:link></li>
			</ul>
		</div>
	</div>

	<div id="data" >
		<div class="titleHotel">
			<p>DATOS EN TIEMPO REAL LUMINOSIDAD</p>
		</div>
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="true" />
			<p:poll interval="1" update="gaugeLuzAmbiente, gaugeLuzArtificial" />
			<p:poll interval="5" update="graphicBar" />

			<div class="graficos" >
				<div class="Row">

					<p:chart type="metergauge" id="gaugeLuzAmbiente"
						model="#{dataSensorHotel.gaugeHotelModel}" styleClass="Column"
						responsive="true">
					</p:chart>

					<p:chart type="metergauge" id="gaugeLuzArtificial"
						model="#{dataSensorHotel.gaugeHotelCalModel}" styleClass="Column"
						responsive="true" >
					</p:chart>
					
					<script>

					
					</script>
				</div>


				<div class="RowBar">

					<p:chart styleClass="ColumnBar" type="bar" id="graphicBar"
						model="#{dataSensorHotel.barModel}" style="height:300px; width: 500px;" />

				</div>

			</div>

		</h:form>
	</div>
	
			<div id="footer">
		<div class="left">
			<p>© 2018. Todos los derechos reservados</p>
		</div>
		<div class="right">
			<!-- 			<p:graphicImage value="recursos/images/LOGO_SEIDOR.png"></p:graphicImage> -->
			<ul>

				<li><a href="#">Términos</a></li>
				<li><a href="#">Privacidad</a></li>
				<li><a href="http://www.seidor.com/content/seidor-com/es.html" target="_blank">Sobre Seidor</a></li>
			</ul>
		</div>
	</div>



</body>
</html>

IoTSensor/WebContent/verData.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Datos</title>
	<link rel="stylesheet" href="recursos/css/estilos.css" />
<link rel="icon" type="image/ico"
		href="recursos/images/icons/Seidor_icon.ico" />
		
		<script
		src="https://maps.google.com/maps/api/js?key=AIzaSyABHAbfBh08A5nlv57wWSNvzFEf-_SdURs"
		type="text/javascript"></script>
		
		<style type="text/css">
		
		
		
		</style>

	<script>
	

            $(document).ready(function () {

                $("body").hide().fadeIn(1000);


            });

        </script>
</h:head>

<body>

<f:metadata>
    <f:viewParam name="nameId" value="#{dataSensor.deviceName}" />
</f:metadata>

<div class="cover"
		style="background-image: url('recursos/images/banner.jpg');">
		<div class="content">
			<div id="figure" class="logo">
				<img src="recursos/images/logoSeidorAzul.png" alt="" width="300" />
			</div>
		</div>
	</div>
		

		<div id="navegacion">
			<div id="nav">
				<ul>
					<li><p:link styleClass="a" outcome="index" value="Salir"></p:link></li>
					<li><p:link styleClass="a"  outcome="mapaSensores" value="Ver Mapa"></p:link></li>
				</ul>
			</div>
		</div>
		



		<div id="data">
		<div class="title">
			<p>DATOS EN TIEMPO REAL</p>
		</div>
			<div class="btnMapa">
				<p:commandButton id="btn" type="button" icon="ui-icon-pin-s"
					value="Mostrar Mapa" onclick="PF('dlg').show();" />			
			</div>
			
			<h:form>
				
				

				<p:growl id="growl" showDetail="true" sticky="true" />

				<p:poll interval="1" update="message" stop="#{dataSensor.stop}" />

				<p:poll interval="1" update="gaugeTemp, gaugeHumidity, graphicTemp, graphicHumidity"/>
				
				<p:poll interval="10" update="graphicTemp, graphicHumidity"/>

				<!--caja perteneciente al grafico GuageModel de temperatura -->
				
				<div class ="graficos">
				<div class="Row">
					<p:chart type="metergauge" id="gaugeTemp" 
						model="#{dataSensor.gaugeTempModel}" styleClass="Column" responsive="true">
					</p:chart>
					
					<p:chart styleClass="Column" type="line" id="graphicHumidity"
					model="#{dataSensor.lineGraphicHumedad}" />
															
				</div>		
			
			<!--caja correspondiente a el grafico lineal -->
			<div class=" Row">				
				<p:chart type="metergauge" id="gaugeHumidity"
						model="#{dataSensor.gaugeHumidityModel}" styleClass="Column" responsive="true">
					</p:chart>
					
				<p:chart styleClass="Column" type="line" id="graphicTemp"
					model="#{dataSensor.lineGraphic}" />
			</div>				
		</div>
				<!--dialogo correspondiente al mapa emergente por sensor -->
				<p:dialog id="gmapDialog" header="Ubicacion del sensor"
					widgetVar="dlg" width="625" height="400" modal="true"
					hideEffect="fade" showEffect="fade" resizable="false">

					<p:gmap id="gmap" center="4.092395,-74.9199007" zoom="18"
						type="HYBRID" mapTypeControl="false" navigationControl="false"
						model="#{ubicacionMB.advancedModel}"
						style="width:600px; height:390px">

						<p:ajax event="overlaySelect"
							listener="#{ubicacionMB.onMarkerSelect}" />

						<p:gmapInfoWindow id="infoWindow">
							<p:outputPanel
								style="text-align: center; display: block; margin: auto">
								<h:outputLabel value="#{ubicacionMB.marker.latlng}" />
								<br />
								<p:link value="#{ubicacionMB.marker.title}" outcome="verData"></p:link>

							</p:outputPanel>
						</p:gmapInfoWindow>
					</p:gmap>
				</p:dialog>

				<!--dialogo perteneciente al mensaje de alerta del sensor -->
				<p:dialog id="message" showEffect="fade" hideEffect="bounce"
					resizable="false" header="Alerta" widgetVar="dlg2" modal="true"
					height="100"
					visible="#{dataSensor.alertaUso and (!dataSensor.aparecioAlerta)}">
					<h:outputText
						value="Alerta: La temperatura es mayor a 25° ¿Desea enviar un correo de aviso?" />
					<br></br>
					<p:commandButton value="Cancelar" icon="ui-icon-locked "
						onclick="PF('dlg2').hide();" />
					<p:commandButton actionListener="#{dataSensor.sendEmail}"
						update="growl" value="Enviar correo" icon="ui-icon-mail-open"
						oncomplete="PF('dlg2').hide();" />
				</p:dialog>



			</h:form>
		</div>

			<div id="footer">
		<div class="left">
			<p>© 2018. Todos los derechos reservados</p>
		</div>
		<div class="right">
			<!-- 			<p:graphicImage value="recursos/images/LOGO_SEIDOR.png"></p:graphicImage> -->
			<ul>

				<li><a href="#">Términos</a></li>
				<li><a href="#">Privacidad</a></li>
				<li><a href="http://www.seidor.com/content/seidor-com/es.html" target="_blank">Sobre Seidor</a></li>
			</ul>
		</div>
	</div>

</body>
</html>